name: 'CifarResNet44'
class_instance:
    _target_: 'pl_models.cifar10_resnet.CifarResNet'
    lr: ${optimizer.lr}
    num_classes: ${dataset.num_classes}
    partial_optimizer: ${optimizer}
    partial_lr_scheduler: ${lr_scheduler}
    partial_adv_attack: ${adv_training}
    num_blocks: [7, 7, 7]
    checkpoint_path: null