defaults:
  - dataset: cifar10
  - model: cifar_resnet18
  - augmentations@train_augmentations: defaults
  - augmentations@eval_augmentations: defaults
  - normalization: defaults
  - training: defaults