defaults:
    - dataset: facescrub_cropped
    - model: resnet18
    - optimizer: defaults
    - lr_scheduler: multi_step_lr
    - transformations@train_transforms: [random_resized_crop, color_jitter, random_horizontal_flip]
    - transformations@eval_transforms: [random_resized_crop, color_jitter, random_horizontal_flip]
    - normalization: defaults
    - training: defaults
    - adv_training: defaults
    - _self_

seed: 42
wandb:
    entity: null
    experiment_name: 'Template Experiment'
    run_name: ${model.name} ${dataset.name} ${wandb.experiment_name}
    offline: false
    project: 'Template_Project'
datamodule:
    _target_: "pl_modules.datamodule.DataModule"
    batch_size: ${training.batch_size}
    dataset_args: null
    dataloader_args:
        num_workers: 8
        shuffle: True
        pin_memory: True
lr_scheduler:
    milestones: [75, 90]
optimizer:
    lr: 0.001
rtpt:
    initials: 'DH'
