_target_: 'torch.optim.lr_scheduler.MultiStepLR'
milestones: ${list:${eval:'(${training.epochs}//4)*1'},${eval:'(${training.epochs}//4)*2'},${eval:'(${training.epochs}//4)*3'}}
gamma: 0.1
last_epoch: -1
verbose: false
_partial_: true